In [1]:
# import required libraries
import pandas as pd
import numpy as np

In [2]:
# Reading the dataset
df=pd.read_csv(r"C:\Users\sv833\Documents\SmartInternz\50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.shape

(50, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [62]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit  state
0  165349.20       136897.80        471784.10      2  192261.83      2
1  162597.70       151377.59        443898.53      0  191792.06      0
2  153441.51       101145.55        407934.54      1  191050.39      1
3  144372.41       118671.85        383199.62      2  182901.99      2
4  142107.34        91391.77        366168.42      1  166187.94      1

In [63]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [66]:
df['State'] = le.fit_transform(df['State'])
df.drop(columns=['State'], inplace=True)

In [67]:
df.head()

R&D Spend  Administration  Marketing Spend     Profit  state
0  165349.20       136897.80        471784.10  192261.83      2
1  162597.70       151377.59        443898.53  191792.06      0
2  153441.51       101145.55        407934.54  191050.39      1
3  144372.41       118671.85        383199.62  182901.99      2
4  142107.34        91391.77        366168.42  166187.94      1

In [68]:
x=df.iloc[:,:-1].values

In [69]:
x

array([[165349.2 , 136897.8 , 471784.1 , 192261.83],
       [162597.7 , 151377.59, 443898.53, 191792.06],
       [153441.51, 101145.55, 407934.54, 191050.39],
       [144372.41, 118671.85, 383199.62, 182901.99],
       [142107.34,  91391.77, 366168.42, 166187.94],
       [131876.9 ,  99814.71, 362861.36, 156991.12],
       [134615.46, 147198.87, 127716.82, 156122.51],
       [130298.13, 145530.06, 323876.68, 155752.6 ],
       [120542.52, 148718.95, 311613.29, 152211.77],
       [123334.88, 108679.17, 304981.62, 149759.96],
       [101913.08, 110594.11, 229160.95, 146121.95],
       [100671.96,  91790.61, 249744.55, 144259.4 ],
       [ 93863.75, 127320.38, 249839.44, 141585.52],
       [ 91992.39, 135495.07, 252664.93, 134307.35],
       [119943.24, 156547.42, 256512.92, 132602.65],
       [114523.61, 122616.84, 261776.23, 129917.04],
       [ 78013.11, 121597.55, 264346.06, 126992.93],
       [ 94657.16, 145077.58, 282574.31, 125370.37],
       [ 91749.16, 114175.79, 294919.57, 12426

In [70]:
y=df.iloc[:,4:5].values

In [71]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state=0)

In [72]:
x_train.shape, x_test.shape

((35, 4), (15, 4))

In [73]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [74]:
# Creating ANN skeleton

regressor = Sequential() # allows to add sequential layers one after the other
regressor.add(Dense(4,activation='relu')) # input layer
regressor.add(Dense(8,activation='relu')) # hidden layer
regressor.add(Dense(10,activation='relu')) # hidden layer
regressor.add(Dense(1,activation='linear')) # output layer (linear activation function is directly propositional to input and is used for regression)

In [75]:
# Compiling ANN model

regressor.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [76]:
x_train.dtype
y_train.dtype

dtype('int32')

In [77]:
# training the model
regressor.fit(x_train,y_train,batch_size=10,epochs = 300)
# 10 inputs in 1 batch

Epoch 1/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 23969980.0000 - mse: 23969980.0000
Epoch 2/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12509703.0000 - mse: 12509703.0000
Epoch 3/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7206288.0000 - mse: 7206288.0000 
Epoch 4/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4525108.0000 - mse: 4525108.0000
Epoch 5/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5038765.5000 - mse: 5038765.5000 
Epoch 6/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3533390.0000 - mse: 3533390.0000
Epoch 7/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3952705.7500 - mse: 3952705.7500
Epoch 8/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3873243.2500 - mse: 3873243.2500 
Epoch 9/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4136394.7500 - mse: 4136394.7500
Epoch 10/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2391067.5000 - mse: 2391067.5000 
Epoch 11/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3193536.2500 - mse: 3193536.25

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3796.5298 - mse: 3796.5298
Epoch 68/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7950.1743 - mse: 7950.1743   
Epoch 69/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4918.9961 - mse: 4918.9961
Epoch 70/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7261.4019 - mse: 7261.4019   
Epoch 71/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2986.7341 - mse: 2986.7341
Epoch 72/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4203.2876 - mse: 4203.2876
Epoch 73/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7848.6650 - mse: 7848.6650   
Epoch 74/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5624.1855 - mse: 5624.1855 
Epoch 75/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3634.8574 - mse: 3634.8574 
Epoch 76/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3385.9453 - mse: 3385.9453
Epoch 77/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8677.6895 - mse: 8677.6895   
Epoch 78/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5690.

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1688.6902 - mse: 1688.6902
Epoch 136/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3337.9944 - mse: 3337.9944 
Epoch 137/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3621.1208 - mse: 3621.1208  
Epoch 138/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1791.3500 - mse: 1791.3500
Epoch 139/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1806.4985 - mse: 1806.4985  
Epoch 140/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2881.3604 - mse: 2881.3604 
Epoch 141/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1150.3424 - mse: 1150.3424
Epoch 142/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1470.3351 - mse: 1470.3351  
Epoch 143/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1117.4705 - mse: 1117.4705
Epoch 144/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1086.6377 - mse: 1086.6377
Epoch 145/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 850.0562 - mse: 850.0562  
Epoch 146/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss:

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 500.0311 - mse: 500.0311 
Epoch 204/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 611.0948 - mse: 611.0948
Epoch 205/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 980.4261 - mse: 980.4261  
Epoch 206/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 715.7802 - mse: 715.7802 
Epoch 207/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 560.5089 - mse: 560.5089
Epoch 208/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 446.6188 - mse: 446.6188
Epoch 209/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 467.2534 - mse: 467.2534
Epoch 210/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 882.9749 - mse: 882.9749   
Epoch 211/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 866.2209 - mse: 866.2209  
Epoch 212/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 875.2925 - mse: 875.2925 
Epoch 213/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 955.1971 - mse: 955.1971   
Epoch 214/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 815.1187 - mse

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 359.3154 - mse: 359.3154 
Epoch 272/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 387.3827 - mse: 387.3827 
Epoch 273/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 437.0815 - mse: 437.0816 
Epoch 274/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 347.4985 - mse: 347.4985 
Epoch 275/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 288.0852 - mse: 288.0852
Epoch 276/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 251.7126 - mse: 251.7126
Epoch 277/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 227.9794 - mse: 227.9794
Epoch 278/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 510.7195 - mse: 510.7195  
Epoch 279/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 279.5299 - mse: 279.5299 
Epoch 280/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 297.5948 - mse: 297.5948
Epoch 281/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 321.3571 - mse: 321.3571 
Epoch 282/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 333.6018 - mse: 333.

In [78]:
# testing the model
y_pred = regressor.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step


In [79]:
y_pred

array([[0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893],
       [0.06916893]], dtype=float32)

In [80]:
from sklearn.metrics import r2_score

In [81]:
r2_score(y_test,y_pred)

-2.96279447273408

In [82]:
y_pred.flatten()

array([0.06916893, 0.06916893, 0.06916893, 0.06916893, 0.06916893,
       0.06916893, 0.06916893, 0.06916893, 0.06916893, 0.06916893,
       0.06916893, 0.06916893, 0.06916893, 0.06916893, 0.06916893],
      dtype=float32)

In [83]:
# comparing the actual and predicted y values
pd.DataFrame({'Actual y_value':y_test.flatten(),'Predicted y_values':y_pred.flatten()}).head(10)

Actual y_value  Predicted y_values
0               1            0.069169
1               0            0.069169
2               1            0.069169
3               1            0.069169
4               1            0.069169
5               2            0.069169
6               2            0.069169
7               2            0.069169
8               1            0.069169
9               1            0.069169

In [84]:
df.head()

R&D Spend  Administration  Marketing Spend     Profit  state
0  165349.20       136897.80        471784.10  192261.83      2
1  162597.70       151377.59        443898.53  191792.06      0
2  153441.51       101145.55        407934.54  191050.39      1
3  144372.41       118671.85        383199.62  182901.99      2
4  142107.34        91391.77        366168.42  166187.94      1

In [85]:
inputx=np.array([[142107.34,91391.77,366168.42,1]])

In [86]:
#testing with random values

regressor.predict(inputx)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step


array([[-18893.51]], dtype=float32)